---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-argo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-argo
    spec:
      containers:
        - image: nginxdemos/hello
          name: hello-argo
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP
              name: hello-argo